### ISSUE TITLE
client stuck

### ISSUE THREAD

**Issue by schmurfy** [zeromq/rbzmq#2]
Hi,
I made a simple zeromq test under ruby ( http://gist.github.com/513982 )
I run the client and the server in any order and they work fine but if i kill the server the client will remains stuck in Receiving state, What is the correct way of handling this case ?

**Comment by bwbuchanan** [comment]
It's not clear to me exactly what behavior you're trying to achieve, and, in any event, this is not something that is specific to the Ruby library.  You should check the archives of the zeromq mailing list, because the topic of how to deal with REQ sockets where the reply is not received has been discussed at length recently.

**Comment by schmurfy** [comment]
thanks i will check there, and yes that's not specific to the ruby library but i wasn't too sure where to ask xD
